core/core.go

https://developer.zendesk.com/rest_api/docs/core/introduction
add CoreAPI base

add CoreAPI base

---

common/paginatable.go
core/trigger.go
test/main.go
zendesk.go
zendesk_test.go

add zendesk_test.go

---

.travis.yml

turn off email notification

---

zendesk/via_types.go
zendesk/via_types_test.go

Add via_types

---

README.md
appveyor.yml

Add appveyor

---

zendesk/zendesk_test.go

Add test cases

---

zendesk/group.go
zendesk/ticket_field.go
zendesk/ticket_form.go
zendesk/trigger.go
zendesk/user.go

try to parse
```json
{
"page": {
"next_page": null,
"previous_page": null,
"count": 1
}
}
```
but, it's not exist.
parse
```json
{
"next_page": null,
"previous_page": null,
"count": 1
}
```

Fix Page field parsing

---

fixture/POST/ticket_fields.json
fixture/POST/triggers.json
zendesk/dynamic_content.go
zendesk/group.go
zendesk/group_test.go
zendesk/ticket_field.go
zendesk/ticket_field_test.go
zendesk/ticket_form_test.go
zendesk/trigger.go
zendesk/trigger_test.go
zendesk/user.go

#57 
Set request payload correctly

Fix #57, Fix terrible bug

---

zendesk/api.go
zendesk/mock/api.go

Will make build fail if the mock client does not implement the API interface

making sure mock client implements api

---

zendesk/group.go
zendesk/group_test.go
zendesk/mock/client.go

Group update & delete

---

fixture/GET/brand.json
fixture/PUT/brands.json
zendesk/brand.go
zendesk/brand_test.go
zendesk/mock/client.go

Add support for brand Get/Update/Delete

---

fixture/GET/ticket_form.json
fixture/PUT/ticket_form.json
zendesk/mock/client.go
zendesk/ticket_form.go
zendesk/ticket_form_test.go

close #51, close #53, close #59

RUD for Ticket form API

---

fixture/GET/attachment.json
zendesk/attachment.go
zendesk/attachment_test.go
zendesk/mock/client.go

Attachment api

---

fixture/GET/trigger.json
fixture/PUT/triggers.json
zendesk/mock/client.go
zendesk/trigger.go
zendesk/trigger_test.go

close #86 
last feature for v0.2.0

RUD Trigger

---

zendesk/collaborators.go
zendesk/collaborators_test.go

Wanted to put together a  proof of concept for the "custom type" i suggested

[Draft] Added a collaborators type

---

zendesk/locale_types_test.go

test only boundary values for coverage.

Add missing test for locale_types

---

zendesk/mock/client.go
zendesk/ticket_form.go
zendesk/ticket_form_test.go

Context support for ticket form

---

zendesk/mock/client.go
zendesk/ticket_field.go
zendesk/ticket_field_test.go

Context support for ticket field

---

zendesk/locale.go
zendesk/locale_test.go
zendesk/mock/client.go

Context support for locale

---

zendesk/api.go
zendesk/dynamic_content.go
zendesk/dynamic_content_test.go
zendesk/mock/client.go

Context support for dynamic content

---

zendesk/mock/client.go
zendesk/user.go
zendesk/user_test.go

Context support for user

---

zendesk/zendesk.go
zendesk/zendesk_test.go

Remove exported http methods

---

fixture/GET/ticket.json
fixture/GET/tickets.json
zendesk/api.go
zendesk/collaborators.go
zendesk/collaborators_test.go
zendesk/mock/client.go
zendesk/ticket.go
zendesk/ticket_test.go

for #92
🍒-picked f3b1b7a from #105 
This PR adds only GetTicket support. Rest of CRUD would be done in other PRs.

Support ticket API (GetTicket)

---

fixture/POST/ticket.json
zendesk/ticket.go
zendesk/ticket_test.go

#92 
Ticket depends on these resources.
- [ticket comment](https://developer.zendesk.com/rest_api/docs/support/ticket_comments) #125 
- [ticket audit](https://developer.zendesk.com/rest_api/docs/support/ticket_audits) #126 
I think it better to separate PR for them.

Ticket creation support

---

zendesk/mock/client.go
zendesk/ticket.go
zendesk/ticket_test.go

Add GetTickets

---

fixture/GET/automation.json
fixture/GET/automations.json
fixture/POST/automations.json
fixture/PUT/automations.json
zendesk/api.go
zendesk/automation.go
zendesk/automation_test.go
zendesk/mock/client.go

Automation support

---

zendesk/attachment.go
zendesk/attachment_test.go
zendesk/brand_test.go
zendesk/ticket_test.go
zendesk/zendesk.go

https://github.com/nukosuke/go-zendesk/issues/155

Fixing issue where api request doesn't use the provided context.

---

.travis.yml

Test on go1.14

---

zendesk/sla_policy.go
zendesk/sla_policy_test.go

For some context this is to fix the following pr: https://github.com/nukosuke/terraform-provider-zendesk/pull/187
Will need this merged and released in order to update the terraform provider

Fixing json key on policy metric

---

zendesk/ticket.go
zendesk/ticket_test.go

Related to https://github.com/nukosuke/go-zendesk/issues/123

Handle Via field in Ticket

---

fixture/GET/ticket_audit.json
fixture/GET/ticket_audits.json
zendesk/Cursor.go
zendesk/api.go
zendesk/cursor.go
zendesk/mock/client.go
zendesk/ticket_audit.go
zendesk/ticket_audit_test.go

add ticket audit api

---

zendesk/ticket_comment.go

Adds via to `TicketComment` in the same manner as #172

Add metadata and via to comments

---

zendesk/ticket.go
zendesk/ticket_comment.go

- #185 
- #186 
- #187 
- #189

Release v0.8.2

---

.github/workflows/ci.yml

https://docs.coveralls.io/parallel-build-webhook

Enable Coveralls parallel build webhook

---

zendesk/attachment_test.go
zendesk/ticket.go
zendesk/ticket_audit_test.go
zendesk/ticket_comment.go
zendesk/ticket_test.go

Make Via field to pointer type

---

.github/workflows/ci.yml

- Add latest go support
- Drop obsoletes

Add support for go1.17 / drop for go1.11, go1.12

---

zendesk/mock/client.go
zendesk/user.go
zendesk/user_test.go
zendesk/zendesk.go

Adding create or update user api and updated the Zendesk client's post to handle 200s.

Adding create or update user api

---

zendesk/mock/client.go

@nukosuke I made a mistake when generating the mocks in my prior PR. I apologize for the inconvenience.

Regenerating Mocks

---

zendesk/api.go
zendesk/mock/client.go
zendesk/organization_membership.go

Adds support for the organization_memberships api endpoint.

Adds organization_memberships support

---

zendesk/api.go
zendesk/custom_role.go
zendesk/mock/client.go

Adds support for the list custom roles endpoint

Adds support for fetching the list of custom roles

---

zendesk/dynamic_content.go
zendesk/mock/client.go

- Add support for Read/Update/Delete dynamic content item

Add missing method for dynamic content item

---

zendesk/dynamic_content.go

Fix create endpoint for dynamic content

---

fixture/GET/webhook.json
fixture/POST/webhooks.json
zendesk/api.go
zendesk/mock/client.go
zendesk/webhook.go
zendesk/webhook_test.go
zendesk/zendesk.go

resolve #211 
- Impl Zendesk webhook CRUD
- Add tests for webhook methods

Add support for webhook API

---

zendesk/organization.go

Many thanks for the library!
this PR is related to #232.
just add the missing fields.
- ExternalId
- Details
- Notes
ref: https://developer.zendesk.com/api-reference/ticketing/organizations/organizations/

add some missing fields to organization

---

zendesk/group.go
zendesk/group_test.go
zendesk/mock/client.go

~~I'm waiting for an API key to test this PR. Feel free to review the code!~~
Seems to work fine!
Reference: https://developer.zendesk.com/api-reference/ticketing/groups/groups/#pagination

Add List Groups pagination

---

.github/workflows/ci.yml
go.mod

* Add support for go1.19
* Drop support for go1.14
* Now minimum support version is go1.15

Fix support golang version

---

zendesk/mock/client.go
zendesk/ticket_comment.go
zendesk/ticket_comment_test.go

Converts a public comment to an internal note

Add 'make comment private' API

---

zendesk/ticket.go

I added a few of fields in the ticket struct to protect against ticket update collisions.
see: https://developer.zendesk.com/documentation/ticketing/managing-tickets/creating-and-updating-tickets/#protecting-against-ticket-update-collisions

Support safe-update

---

fixture/GET/apps.json
go.mod
go.sum
zendesk/api.go
zendesk/app.go
zendesk/app_test.go
zendesk/mock/client.go

GET /api/v2/apps/installations
https://developer.zendesk.com/api-reference/ticketing/apps/apps/

Add 'list app installations' API

---

fixture/GET/ticket.json
zendesk/ticket.go

Recent release: https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#json-format

Add support for ticket custom ID field

---

zendesk/mock/client.go
zendesk/organization.go

Add the `GetOrganizationByExternalID` method to `OrganizationAPI` interface

feat: add get organization by external id to OrganizationAPI interface

---

zendesk/user.go

Supports offset pagination, per the docs: https://developer.zendesk.com/api-reference/ticketing/users/users/#search-users

Add pagination to user search endpoint

---

fixture/GET/ticket_comments.json
zendesk/cursor.go
zendesk/mock/client.go
zendesk/ticket_comment.go
zendesk/ticket_comment_test.go
zendesk/zendesk.go

Add cursor pagination for list ticket comments.

---

fixture/GET/organization_fields.json
fixture/POST/organization_fields.json
zendesk/api.go
zendesk/custom_field_option.go
zendesk/mock/client.go
zendesk/organization_field.go
zendesk/organization_field_test.go

Add methods to list and create Organization custom fields.

Add custom organization fields (list and create) methods

---

zendesk/custom_object.go

Adds `Ids` filter to List Custom Object Records API: https://developer.zendesk.com/api-reference/custom-data/custom-objects/custom_object_records/#list-custom-object-records

feat: add the ids filter option for the list custom object records api

---

script/codegen/main.go

fix file close bug

---

zendesk/ticket_metrics.go

This PR add support for the [ticket metrics](https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_metrics/) endpoints. 
I tried to follow existing implementations. Not sure if there is anything else you want me to do. Please let me know!
I've tested it manually with a private zendesk instance.

feat: Add ticket metrics support
