- common/service.go
- core/core.go
- core/trigger.go
- zendesk.go
Any other service must inherit `common.Service` to refer member
- `HTTPClient` : `*http.Client` HTTP client of `net/http`
- `BaseURL` : `*url.URL` Zendesk API URL including subdomain
- `UserAgent` : `string` user-agent of zenform/go-zendesk
```go
package some
import (
"github.com/zenform/go-zendesk/common"
)
type some.Service common.Service
```
> add common.Service and core.CoreService inherit it

- core/trigger.go
fix #9 
refer action `value` as below
```go
// string type
action.Value.AsString
// []string type
action.Value.AsStringArray
```
It depends on `field` value which to refer.
> unmarshal trigger actions value according to type (string or []string)

- zendesk/error_test.go
- zendesk/zendesk.go
- zendesk/zendesk_test.go
Creating error type inspired by https://github.com/fprimex/zdesk/blob/master/zdesk/zdesk.py#L68-L75.
Error exposes the zendesk http response to the client as well as the response body.
> Adding error type that exposes the response from zendesk

- .travis.yml
- appveyor.yml
- go.mod
- go.sum
I'm planning to remove `dep` when Go 1.9 and 1.10 would be obsolete.
But it is supported only for these versions for now.
> Use go modules on supported versions

- zendesk/error_test.go
- zendesk/zendesk.go
- zendesk/zendesk_test.go
Determined through testing that downstream clients could not read the ZendeskError body. Refactored the error a bit to allow clients to read HTTP response body downstream.
> Updates to the zendesk Error type

- zendesk/ticket_field.go
- zendesk/ticket_form.go
- zendesk/trigger.go
- zendesk/user.go
- zendesk/zendesk.go
fix #80 
Updated all `Client` receiver
> Fix non-pointer receiver

- zendesk/user_field.go
#70 
Add context support for GetUserFields()
But, I think that we don't have to support this API at v0.3.0 because user_field has no test and fundamental CRUD methods are missing. It will be scheduled on milestone >= v0.3.1
> Add context support for GetUserFields()

- README.md
- zendesk/group.go
- zendesk/group_test.go
- zendesk/mock/client.go
> Context support for Group API

- zendesk/mock/client.go
- zendesk/trigger.go
- zendesk/trigger_test.go
> Context support for trigger

- zendesk/brand.go
Fix #128 
`ticket_field_ids` is not attribute of brand, but `ticket_form_ids`.
This also should be patched to v0.2.1
> Fix field of brand, ticket_form_ids

- fixture/GET/target.json
- fixture/GET/targets.json
- fixture/POST/target.json
- fixture/PUT/target.json
- zendesk/api.go
- zendesk/main_test.go
- zendesk/mock/client.go
- zendesk/target.go
- zendesk/target_test.go
Implemented initial support for operating on targets. Only `email_target` and `http_target` are currently supported, but adding support for other target types is relatively straightforward.
> Target support

- fixture/GET/ticket_custom_field.json
- zendesk/ticket.go
- zendesk/ticket_test.go
Upon further testing it was revealed that Zendesk does return nil and
boolean values for custom fields. Numeric and decimal type custom
fields are returned as strings.
This is a breaking issue for v0.4.2 since upon ticket creation Zendesk returns the created ticket itself, which may be full of nils from empty custom fields.
> Issue #122 Forgot to add nil and bool types.

- fixture/GET/ticket_comments.json
- fixture/PUT/ticket.json
- zendesk/ticket.go
- zendesk/ticket_comment.go
- zendesk/ticket_comment_test.go
This PR contributes to #125 by adding some basic ticket comment support. I needed this for a project and noticed this functionality doesn't exist. I figured I might as well contribute upstream while I'm at it!
This is a potential gotcha that requires an odd solution.
If we use `omitempty` on that attribute, any TicketComments that have `Public: false` will be filtered out causing ALL comments to be public. Alternatively, if we remove that flag, the default for the package would be private comments which is not inline with the Zendesk API. Using `*bool` is a good compromise so we can have 3 states (`true`/`false`/`nil`). We'd have a default of public comments while still offering private ones.
The downside is confusion with generating new TicketComment structs. I added some utility …
> Add TicketComment functionality

- go.mod
- zendesk/ticket_comment.go
To have attachement attached to tickets the `uploads` field need to be present. 
See this article https://support.zendesk.com/hc/en-us/articles/223137947-Attaching-files-to-tickets-via-API
> Adds upload field for comments

- zendesk/trigger.go
Values inside `TriggerCondition` can be any JSON value: `number`, `string`, `boolean` and even `null`. Therefore we need the `Value` field to be an `interface{}`. 
Fixes #177
> Unmarshal TriggerCondition Value to interface{}

- .golangci.yml
- go.sum
- go mod tidy
- remove unused config .golangci.yml
- [GolangCI](https://golangci.com/) has been closed and now we use [HoundCI](https://www.houndci.com/) instead
> Cleanup obsolete

- zendesk/mock/client.go
- zendesk/ticket_comment.go
- zendesk/ticket_comment_test.go
This allows us to get TicketComment.ID if necessary immediately after
creation.
> Return ticket comment after creating

- fixture/GET/macro.json
- fixture/GET/macros.json
- fixture/POST/macro.json
- fixture/PUT/macro.json
- zendesk/api.go
- zendesk/macro.go
- zendesk/macro_test.go
- zendesk/mock/client.go
I wrote some APIs support about macro.
Could you merge for original ?
New support APIs is below
+ [ListMacros](https://developer.zendesk.com/rest_api/docs/support/macros#list-macros)
+ [ShowMacro](https://developer.zendesk.com/rest_api/docs/support/macros#show-macro)
+ [CreateMacro](https://developer.zendesk.com/rest_api/docs/support/macros#create-macro)
+ [UpdateMacro](https://developer.zendesk.com/rest_api/docs/support/macros#update-macro)
+ [DeleteMacro](https://developer.zendesk.com/rest_api/docs/support/macros#delete-macro)
> Add macro API support

- zendesk/zendesk.go
I had a problem when I wanted to authenticate using OAuth2 token as follows, so I dealt with it.
```go
ctx := context.Background()
ts := oauth2.StaticTokenSource(
&oauth2.Token{AccessToken: os.Getenv("ZENDESK_OAUTH2_TOKEN")},
)
tc := oauth2.NewClient(ctx, ts)
z, _ := zendesk.NewClient(tc)
ifz.SetSubdomain(os.Getenv("ZENDESK_SUBDOMAIN"))
ticket, _ := z.GetTicket(ctx, int64(2))
```
got
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
```
Please review.
> add nil check to z.credential

- zendesk/ticket.go
This struct addition allows for creating a ticket for requesters that do not yet exist as zendesk users:
https://develop.zendesk.com/hc/en-us/articles/360059146153#creating-a-ticket-with-a-new-requester
> Add requester struct and field for Ticket

- zendesk/collaborators.go
- zendesk/collaborators_test.go
- zendesk/ticket_test.go
Many thanks for the library!
Here's a PR to fix a small bug when json-marshalling a `Ticket`.
This happens, e.g. when creating a Ticket in [ticket.go:242](https://github.com/nukosuke/go-zendesk/blob/master/zendesk/ticket.go#L242)
which marshals the passed Ticket in [zendesk.go:117](https://github.com/nukosuke/go-zendesk/blob/0dfede2ee6f18a8c2586ccba2ede2bf9b4b042ac/zendesk/zendesk.go#L117)
The json sent to the server is then something like this:
```json
{
"ticket": {
"//": "...",
"collaborators": {},
"//": "...",
}
}
```
Although it should be `"collaborators" : []` because it's clearly a list. 
The reason is, that `json.Marshal(...)` is called on a value of `Ticket` instead of a pointer, i.e. the function `func (c * Collaborators) MarshalJSON() ([]byte, error)` is never called.
In …
> Bugfix json-marshal collaborators in Ticket

- zendesk/api.go
- zendesk/mock/client.go
- zendesk/zendesk.go
Previous commit added methods to query not-yet-implemented API endpoints (https://github.com/nukosuke/go-zendesk/commit/67acb1580313dd11b0a60b13ff39dcc909aad617), but didn't expose these in the client interface so they are still not callable. Adding them here.
Tested this locally and was able to query an arbitrary endpoint
> expose Get and Put methods in API interface

- zendesk/ticket.go
`omitempty` doesnt work on empty times unless they're pointers.
We don't have `DueAt` set on our tickets and `omitempty` on `time.Time` only works when its a pointer, as `isZero`  returns `false` for an empty `time.Time{}` where as `isZero` will return `true` when a pointer is not existent.
if `DueAt` is not a pointer, then when I get the ticket back from the API, it'll set `DueAt` to `0001-01-01 00:00:00 +0000 UTC` and similarly, if i don't set it on a `Ticket` i update, then it'll send it to the API as `0001-01-01 00:00:00 +0000 UTC`.
This patch resolves this issue.
> Allow omitempty to work for DueAt time.Time

- zendesk/ticket.go
- zendesk/ticket_test.go
Same issue as here https://github.com/nukosuke/go-zendesk/pull/214
Changing time fields and structs in Ticket struct to pointers so they will be omitted in the JSON request body.
> Use pointers in ticket struct to have fields omitted by omitempty.

- zendesk/group.go
Added the `default` and `description` fields
reference: https://developer.zendesk.com/api-reference/ticketing/groups/groups/
> Add missing Group fields

- zendesk/user.go
Providing a link to the users photo is much easier than managing an
upload, and is supported via the normal APIs.
> Add support for remote photo URL

- fixture/GET/organization_memberships.json
- fixture/POST/organization_membership.json
- fixture/PUT/organization_membership.json
- zendesk/mock/client.go
- zendesk/organization_membership.go
- zendesk/organization_membership_test.go
Hi, thanks for the library!  
In my use case I have to deal with [multiple orgs in Zendesk](https://support.zendesk.com/hc/en-us/articles/4408838140314-Enabling-multiple-organizations-for-users), so I am adding a few methods that I needed:
- `CreateOrganizationMembership`
- https://developer.zendesk.com/api-reference/ticketing/organizations/organization_memberships/#create-membership
- `SetDefaultOrganization`
- https://developer.zendesk.com/api-reference/ticketing/organizations/organization_memberships/#set-organization-as-default
> Add methods for creating org memberships and setting default org (membership) for user

- appveyor.yml
- go.mod
- go.sum
- zendesk/credential.go
- zendesk/credential_test.go
- zendesk/zendesk.go
- zendesk/zendesk_test.go
Zendesk OAuth tokens must use the Bearer prefix.
Question to maintainers: Can we bump the go.mod to 1.19? I tried doing it in my commits, but I think the appveyor build system might be using a Go binary of a lower version, I couldn't quite figure it out.
> Add support for Bearer tokens

- zendesk/organization.go
Add a function to search Organizations by External ID, using this API:
https://developer.zendesk.com/api-reference/ticketing/organizations/organizations/#search-organizations-by-external-id
> Add "Search Organizations by External ID" function

- zendesk/mock/client.go
- zendesk/webhook.go
The result of GetWebhook doesn't contain the signing secret. This isn't a problem of this package, it's simply that Zendesk API doesn't return the signing secret field in the payload. In order to receive it it's necessary to call a separate endpoint.
> Add GetWebhookSigningSecret

- zendesk/error.go
Since every errors from each API will be wrapped by the Error type. Here i add a new function to initialize the Error type publicly. Typically, this function will be useful for unit testing and mocking purposes in the client side to test their behavior by the API response.
> feat: add NewError function

- zendesk/error.go
Turns out that the wrapped error from each API is a value type of `Error`. Then we need to make the `NewError` returns the same type.
> return value type of Error on NewError

- fixture/PUT/redact_ticket_comment.json
- zendesk/ticket_comment.go
- zendesk/ticket_comment_test.go
> Add ticket comment redaction

- fixture/PUT/redact_ticket_comment_attachment.json
- zendesk/attachment.go
- zendesk/attachment_test.go
> Add support for ticket comment attachment redaction

- zendesk/mock/client.go
- zendesk/user.go
- zendesk/user_test.go
Add function to fetch Users for an organization:
https://developer.zendesk.com/api-reference/ticketing/users/users/#list-users
GET /api/v2/organizations/{organization_id}/users
> Add list users by Organization

- zendesk/mock/client.go
- zendesk/ticket.go
- zendesk/ticket_test.go
Use the get tickets API but with the organization id parameter.
https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#list-tickets
(GET /api/v2/organizations/{organization_id}/tickets)
> feat: add organization tickets function

- zendesk/ticket_comment.go
The include users didn't returned the list of users as described in the documentation:
https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_comments/#parameters
> fix: add include users in ticket comments API

- zendesk/mock/client.go
- zendesk/view.go
Adding pagination and sorting that was missing from the tickets from view function.
The new parameters will break code that used the previous version of the function.
> add pagination and sorting options to tickets from view API

- zendesk/api.go
- zendesk/custom_object.go
- zendesk/mock/client.go
- zendesk/zendesk.go
Introduce the new [custom_objects_v2](https://developer.zendesk.com/api-reference/custom-objects/introduction/).
The code allows the usage of the following APIs:
- CreateCustomObjectRecord
- SearchCustomObjectRecords
- ListCustomObjectRecords
- ShowCustomObjectRecord
- UpdateCustomObjectRecord
> Custom objects v2

- zendesk/mock/client.go
- zendesk/ticket.go
- zendesk/ticket_test.go
1. Added Cursor Based Pagination support for get tickets method
2. Added Iterator for get tickets, by default, the iterator will use CBP to retrieve tickets.
Example to use the Iterator:
ops := zendesk.NewPaginationOptions()
it := client.GetTicketsEx(context.Background(), ops)
for it.HasMore() {
tickets, err := it.GetNext()
if err == nil {
for _, ticket := range tickets {
println(ticket.Subject)
}
}
}
> Added Cursor Based Pagination support for get tickets

- zendesk/custom_object.go
- zendesk/mock/client.go
Adds a function to the custom object v2 to use:
https://developer.zendesk.com/api-reference/custom-objects/custom_object_records/#search-custom-object-records
> feat: add SearchCustomObjectRecords function

- zendesk/ticket.go
There are times that `group_id` is being returned as string instead of number when using  [Show Changes to Ticket](https://developer.zendesk.com/api-reference/ticketing/business-rules/macros/#show-changes-to-ticket) endpoint and causes json unmarshal to fail
```
json: cannot unmarshal string into Go struct field Ticket.result.ticket.group_id of type int64
```
Changing the type of Ticket.GroupID with `json.Number` seems to solve the issue.
> Unmarshal support for Ticket GroupID

- zendesk/ticket.go
> Fix Requester struct incompatibilities (issue #307)
